### ISSUE TITLE
List MRs/Issues with multiple assignees/authors

### ISSUE THREAD

**Issue by bmeneguele** [xanzy/go-gitlab#1097]
Through API it's possible to request a list of MRs and/or issues with multiple assignees and/or authors.
A way of doing so is as follows:
```
https://gitlab.com/api/v4/projects/:id/merge_requests?assignee_id=<id>&assignee_id=<id>
```

But I don't see a way of performing this request using the lib.
Am I missing something or is it indeed not supported yet?

**Comment by svanharmelen** [comment]
This is indeed not supported. Most likely because the docs don't describe this option.

The page https://docs.gitlab.com/ce/api/merge_requests.html#list-merge-requests indicates only a single integer can be used for the fields you mentioned. Looking at (for example) `approver_ids`, this one does describe that it takes an array. So not sure how to handle this one...

**Comment by bmeneguele** [comment]
Ah, ok, I see your point. I was trying it out in order to find the same functionality the webui has, but if that's not officially documented, we should not expect the behavior to be stable enough to use. I agree with it.

Well, ok then. Thanks for the feedback.
