### ISSUE TITLE
Help to add retries and timeouts

### ISSUE THREAD

**Issue by JohnWillker** [xanzy/go-gitlab#1416]
Hi, 
First of all, this is a nice project and I use it a lot.
But let me ask some questions:
Is there's some way to add retries and timeouts to HTTP requests?

I have noticed that some functions have a request option:
```go
func (s *ProjectsService) ListProjects(opt *ListProjectsOptions, options ...RequestOptionFunc) ([]*Project, *Response, error)
```

Maybe this is a noob question, but how could be configured the `RequestOptionFunc` request retries and timeouts?

**Comment by M0roSan** [comment]
IIUC, it's at client level instead of at requestOption.
you wanna use [WithCustomRetry](https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L71-L76) for retry,  bring your own httpClient with timeout setting and use [WithHttpClient](https://github.com/xanzy/go-gitlab/blob/master/client_options.go#L78-L84)

**Comment by JohnWillker** [comment]
Thanks, @M0roSan, this was helpful.
