### ISSUE TITLE
Urlencoded project path fails with 404

### ISSUE THREAD

**Issue by bryanhelm** [xanzy/go-gitlab#1675]
It appears when I pass a urlencoded project path for a project ID, it fails due to being url decoded in building the url for the gitlab api call. The result is a 404. It works fine if I pass a numeric string project ID. This looks to have been previously reported in issue #632, but closed, and other people are complaining about having to do the urlencoding, but seem to be saying it works if they encode it. I am not seeing that behavior. I have tried the Jobs.ListPipelineJobs and the Projects.GetProject APIs, and in both cases I get a 404 and it displays the failed url containing the project path with / instead of %2F. I am reading a url in a trace log that includes a project path, then trying to use that in an API call, and I cannot figure out a way to get a numeric ID because of this failure. Any advice?

This is the form of the problem, but not using real values:
projectID := "root%2fgroup%2fsubgroup%2fproject"  // url.PathEscape("root/group/subgroup/project")
project, _, err := client.Projects.GetProject(projectID, &GetProjectOptions{})
if err != nil {
    fmt.Println(err)
}

Output is:
GET https://gitlab.ourhost.net/api/v4/projects/root/group/subgroup/project: 404 {message: 404 Project Not Found}

Note the url has the %2f urldecoded back to /

**Comment by bryanhelm** [comment]
I confirmed via curl that the direct gitlab API call works if the project is urlencoded so / is %2F.

**Comment by ahotelko** [comment]
Problem still exists in my case. Tried it with:

`GetFileOptions_tlg_details:= & gitlab.GetFileOptions {
			Ref: gitlab.String("main"),
		}
	    //fetching json response from project's json file 
tlg_details, resp, err:= gitlab_client.client.RepositoryFiles.GetFile(175346, "public/test/test.yml", GetFileOptions_tlg_details)`
and with the encoded part
`tlg_details, resp, err:= gitlab_client.client.RepositoryFiles.GetFile(175346, "public%2Ftest%2Ftest.yml", GetFileOptions_tlg_details)`

both get into an error:
`GET https://gitlab***/api/v4/projects/175346/repository/files/public/test/test.yml 404 {message: 404 File Not Found}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x678b0b]`

**Comment by svanharmelen** [comment]
Interesting panic... Can you share the rest of the panic output so I can see where in code this happens? Or is the panic triggered by something in your own code?

Again (just FYI) the lib already encodes the path, so you should just give it a plain text path when using this package. So the test with the encoded path doesn't make sense here.

Can you share the cURL command you tried that did work?  And are you 100% sure that in both cases you are using the same token?

And lastly, maybe you can add a bit of logging in the `do` call (in `gitlab.go`) to see the resulting request that will be made in order to check/verify what the encoded path looks like.

**Comment by ahotelko** [comment]
Hi yes, think so too. Panic is triggered by something in the code, because of the decoding of the file.
Curl command is in the attachment.
How should i add logging in the do call?

**Comment by ahotelko** [comment]
`curl --header "PRIVATE-TOKEN: *********" https://gitlab.****.de/api/v4/projects/175346/repository/files/public%2****%2Ftop-level-groups%2Ftlg-details.json?ref=main
{"file_name":"tlg-details.json","file_path":"public/******/top-level-groups/tlg-details.json","size":175008,"encoding":"base64","content_sha256":"78b935d4cc4ef5856013e8fdf27a4b5c1d920888eeca3ac731ade1140cc6512c","ref":"main","blob_id":"b2583d8f350498*******bf874c39166be7c6dee4b","commit_id":"********","last_commit_id":"1********1dc6d76fea","execute_filemode":false,"content":"WyAgICAKCXsKCQkiZ3JvdXBJZCI6IDQsCgkJIm9yZyI6ICJEZXV0c2NoZSBUZWxla29tIElUIEdtYkgiCgl9LAoJewoJCSJncm91cElkIjogMTgsCgkJIm9yZyI6ICJEZXV0c2NoZSBUZWxla29tIElUIEdtYkgiLAoJCSJwcm9qZWN0QWRtaW4iOiAiYWxleGFuZGVyLmZyaXR6QHRlbGVrb20uZGUiCgl9LAoJewoJCSJncm91cElkIjogMTQ0LAoJCSJvcmciOiAiRGV1dHNjaGUgV`

**Comment by svanharmelen** [comment]
Probably easiest to add this snippet somewhere [here](https://github.com/xanzy/go-gitlab/blob/master/gitlab.go#L784):

```go
dump, err := httputil.DumpRequestOut(req, true)
if err != nil {
	log.Fatal(err)
}
fmt.Printf("Outgoing request:\n\n%q\n", dump)
```

**Comment by P15233971** [comment]
I've also noticed this happening with groups via the terraform provider which internally runs `group, _, err = client.Groups.GetGroup(fullPathData.(string), nil, gitlab.WithContext(ctx))` - I imagine the issue may be similar with projects?

Manually passing the encoded url into a curl command fetches nested groups as expected, but when passing the normal (unencoded) url via the provider I get a 404. Fetching top-level groups (i.e no nested groups) works fine when using the provider. 

An example of the error I get when passing the full_path of `"top/nested"`: 
`GET https://gitlab.com/api/v4/groups/top/nested: 404 {message: 404 Group Not Found}`

I get the same error when passing the pre-encoded path as a hardcoded string or when using the `urlencode` function. Interestingly it always resolves to the same url in the api call (see error above). 

Although this issue is through use of the provider, it doesn't seem to change anything when making the `GetGroup` call, so it doesn't appear to be an issue with the provider to me.

**Comment by svanharmelen** [comment]
Any updates on this one? If not I'm going to close the issue in a little while...

**Comment by svanharmelen** [comment]
Closing as stale... Feel free to reopen in the future if applicable.
