### ISSUE TITLE
Our service has a scenario where we need to use both V3 and V4 api, is there a recommended solution?

### ISSUE THREAD

**Issue by li-jin-gou** [xanzy/go-gitlab#1860]
v3 branch: https://github.com/xanzy/go-gitlab/tree/f-api-v3. I've seen this branch, and my current thinking is that vendor a copy of the code for this branch

**Comment by svanharmelen** [comment]
Hi @li-jin-gou, not sure how you can make that work... That branch doesn't use Go modules yet so I think vendoring and using it locally is probably your best bet.

The code in that branch is no longer maintained, so since it will not get any updates you can also just copy the code into a local package (directory) within your application and use it from there.

**Comment by li-jin-gou** [comment]
> not sure how you can make that work... That branch doesn't use Go modules yet so I think vendoring and using it locally is probably your best bet.
> 
> The code in that branch is no longer maintained, so since it will not get any updates you can also just copy the code into a local package (directory) within your application and use it from there.

Thanks for the reply.
