### ISSUE TITLE
Requires a set of APIs that support context

### ISSUE THREAD

**Issue by TIEDPAG** [xanzy/go-gitlab#1944]
In the implementation of golang, context should be supported to be passed in to cancel the api call.

For example
```golang
// Current
project, _, err := git.Projects.CreateProject(p)
// Context API
project, _, err := git.Projects.CreateProjectContext(context.Backgroup(), p)
```

**Comment by svanharmelen** [comment]
Hi @TIEDPAG while I understand that in some cases this format makes sense, I'm not really open to changing that throughout the package.

Especially since there already is a way (through maybe a little bit less ergonomic) to make use of contexts by passing this request option: https://github.com/xanzy/go-gitlab/blob/main/request_options.go#L30

Hope you can use tat approach instead...
