### ISSUE TITLE
Invalid struct for MergeCommentEvent.

### ISSUE THREAD

**Issue by afking** [xanzy/go-gitlab#227]
Does not correctly unmarshal to *MergeRequest for MergeCommentEvent struct: https://godoc.org/github.com/xanzy/go-gitlab#MergeCommentEvent, as the API returns a structure similar to MergeRequestEvent: https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#comment-on-merge-request.

**Comment by svanharmelen** [comment]
Can you share some more details @afking? I'm not sure I understand what you mean.

Do you have an example of the error you get? And/or some example code that shows the problem?

**Comment by afking** [comment]
@svanharmelen the struct `MergeCommentEvent` has a field `MergeRequest` of type `*MergeRequest`, however I think it should be the same as `MergeEvent.ObjectAttributes` instead.

```go
var e gitlab.MergeCommentEvent
err := json.Unmarshal(data, &e); err != nil {
    panic(err)
}
if e.MergeRequest.SHA == "" {
    panic("missing sha!")   //  data.merge_request.last_commit.id
}
```
Maybe I'm unmarhsalling to the wrong struct for the webhook events?

**Comment by svanharmelen** [comment]
I seems the problem is that the `MergeRequest` struct is used in two API calls (here and here)

The outputs received are 99% identical, but it looks like just a few fields are not populated in the `MergeCommentEvent`.

Not sure how to proceed with this other that making two separate structs. Maybe that would also be the correct solution for issue #239

**Comment by svanharmelen** [comment]
This issue is solved by PR #245

**Comment by afking** [comment]
@svanharmelen thanks for the fix! This library has saved me a lot of time.

**Comment by svanharmelen** [comment]
Thanks, that's good to hear 👍
