### ISSUE TITLE
Rename repo to xanzy/gitlab

### ISSUE THREAD

**Issue by mvdan** [xanzy/go-gitlab#23]
The package name is `gitlab` while the repo name is `go-gitlab`. This works, but results in confusing usage:

```
import (
	"github.com/xanzy/go-gitlab"
)

func foo() {
	git := gitlab.NewClient(nil, "yourtokengoeshere")
}
```

Where is `gitlab` being declared or imported? This is an extreme case, but if all packages did this, complex programs would be a mess. You could go around this as a user by explicitly importing `gitlab "github.com/xanzy/go-gitlab"`, but that's really unnecessary.

Moreover, the Go authors discourage calling packages or programs `go-*` simply because they are written in Go. You may think that calling your repo `gitlab` might confuse people with the GitLab reo itself, but it's easy to tell apart since one is a Ruby app and another a Go package.

**Comment by svanharmelen** [comment]
@mvdan I see your point, yet I think this is pretty common. That doesn't make it the right pattern of course, but it's also not something a Go developer should be puzzled about.

Also I know about the calling packages or programs `go-*` simply because they are written in Go is discouraged. But in this case I believe the current name makes a lot of sense as it tells you all you need to know... It is a GitLab client for the Go language.

If you look at all the other repo names for GitLab API clients (here: https://about.gitlab.com/applications/) you'll see that quite a few have similar names: `python-gitlab`, `backbone-gitlab`, `php-gitlab-api`, `java-gitlab-api`.

Lastly I think that changing the import URL at this point in time isn't a user friendly thing to do. So long story short, I believe we should not change this and will close this issue as a _won't fix_.

Thanks!

**Comment by mvdan** [comment]
Fair enough. I don't see why you think it wouldn't be user friendly, though - github would redirect the old path to the new one. So all current imports, clones and links would continue to work.
