### ISSUE TITLE
VisibilityValue consistency

### ISSUE THREAD

**Issue by nogs** [xanzy/go-gitlab#356]
Just wondering if there is any reason why VisibilityValue is handled the same in all type definitions which use it.

Just a quick search, https://github.com/xanzy/go-gitlab/search?utf8=✓&q=VisibilityValue&type=, shows that event_types and projects define it as Visibility VisibilityValue, whereas groups, snippets and project_snippets define it as Visibility *VisibilityValue.

Should they be handled consistently across all types?

**Comment by svanharmelen** [comment]
Hi @nogs, the difference is related to what the structs are used for. The structs that are used to unmarshal responses don't use pointers, struct used to define request options do.

In short this is because in Go all types have a zero value. So when you want to make an API call to update a group description, you want that field to be the only field/value send. When using pointers the zero value is `nil` and so the zero value will not be send (when also adding `omitempty` to the fields).

**Comment by nogs** [comment]
OK, makes sense, was just a bit confusing when trying to get something working the other week.  Will have another look at the code I have and see if I can find a more concrete example, but will close this for now.
