### ISSUE TITLE
Support for the upcoming releases and release links apis

### ISSUE THREAD

**Issue by juranki** [xanzy/go-gitlab#546]
Looks like Gitlab 11.7 will promote [Releases](https://docs.gitlab.com/ee/user/project/releases/index.html) from a tag extension to a top level feature. 

Two new apis are added for managing releases:
- [Releases](https://docs.gitlab.com/ee/api/releases/index.html), and
- [Release links](https://docs.gitlab.com/ee/api/releases/links.html)

It would be great if go-gitlab would cover the new API's

**Comment by juranki** [comment]
I started working [towards a PR](https://github.com/xanzy/go-gitlab/compare/master...juranki:releases) and immediately bumped into a naming issue.

Tags api has also some support releases and defines a [Release](https://github.com/xanzy/go-gitlab/blob/master/tags.go#L45) type.

Releases api adds a lot more content to the same concept. I named it [ProjectRelease](https://github.com/juranki/go-gitlab/blob/releases/releases.go#L20), for now. Should I continue with this, or do you have better ideas?

**Comment by svanharmelen** [comment]
Hi @juranki, I wonder if we could use the same struct in both places? Guess that depends at what fields the API is able to return when requesting a tag, so maybe we should check the Gitlab source code to see if that would work.

If not, I think I feel more for renaming the existing `Release` struct to `TagRelease`. Or maybe even better, just make it an inline struct if it only contains the `TagName` and `Description` fields. I very much doubt if anyone is using those struct directly, so that should be a very low impacting breaking change.

But let's first check is they maybe share the same fields and that one struct can be used in both places.

**Comment by svanharmelen** [comment]
Thanks for the PR @juranki!
