### ISSUE TITLE
GetMergeRequest vs GetMergeRequestChanges

### ISSUE THREAD

**Issue by nalbury-handy** [xanzy/go-gitlab#855]
Both of these seem to return a pointer to a MergeRequest struct? Just wondering to why I'd use one vs the other? I'm specifically trying to parse merge request changes, but was surprised to see it just returns the entire MR.

**Comment by svanharmelen** [comment]
Looking at the GitLab docs, the difference is indeed the `changes` being added to the response or not. So the latter one returns additional info, but since the rest of the response is so similar it didn't make sense to create (IMO) a dedicated struct for it.

So when you only want the MR details you can use `GetMergeRequest` (which will always have an empty slice for the `changes` field) and when you (also) want the changes from a MR you can use `GetMergeRequestChanges`.

**Comment by nalbury-handy** [comment]
Awesome, thanks!
